### ISSUE TITLE
Two questions (FAN & placement of the CO2-sensor) and a hint... :-)

### ISSUE THREAD

**Issue by Bascht74** [LaskaKit/ESP-Vindriktning#18]
Hi, i ordered 5 peaces here: https://www.laskakit.cz/laskakit-esp-vindriktning-esp-32-i2c/ together with the CO2-sensor (https://www.laskakit.cz/laskakit-scd41-senzor-co2--teploty-a-vlhkosti-vzduchu/).

Hint: I forgot to order the cable, maybe you guys could place a link for that here on github, so that other people won't forget it in the future. 

I have two questiosns about the installation: 
1. Where is the ideal place to put the CO2-sensor in the housing?
2. How do I change the FAN voltage to 3.3V? I read that ther should be a jumper that I could switch (see https://github.com/LaskaKit/ESP-Vindriktning/issues/8#issuecomment-1370692918), but there is no jumper on my board. Maybe you have a hint for me.

Thx for your work! I wanted to support it so I ordered at your shop :-)

Sebastian

**Comment by Konstantin-G** [comment]
Hi,
1. it is better to put outside, added printed case 
2. there is solder jumper on PCB.
