### ISSUE TITLE
Question: Would work with IKEA VINDSTYRKA as well?

### ISSUE THREAD

**Issue by vsisl** [LaskaKit/ESP-Vindriktning#21]
Hi,

Would the [LaskaKit ESP-VINDRIKTNING ESP-32 I2C board](https://www.laskakit.cz/laskakit-esp-vindriktning-esp-32-i2c/) (and the codebase) also work with the [IKEA VINDSTYRKA](https://www.ikea.com/cz/cs/p/vindstyrka-senzor-kvality-vzduchu-chytre-40498234/) device?

**Comment by Konstantin-G** [comment]
We have no idea. Don't have VINDSTYRKA to check and test.

**Comment by vsisl** [comment]
Thanks for a quick reply @Konstantin-G !

I have the VINDSTYRKA device. If there was interest from LaskaKit, I could test if it works with your board. I'm based in Czech Rep.

**Comment by Konstantin-G** [comment]
Yeah , sure, it would nice
