### ISSUE TITLE
Fan noise

### ISSUE THREAD

**Issue by magtimmermans** [LaskaKit/ESP-Vindriktning#5]
Is there a way to lower the fan noise for example connect it to 3.3 v?

**Comment by Konstantin-G** [comment]
Maybe?

**Comment by magtimmermans** [comment]
Would be nice. Further great product!

**Comment by magtimmermans** [comment]
I thought when you run it on 3v3 it runs slower. But I will try your suggestion as well.

**Comment by Konstantin-G** [comment]
In V3.0 we added jumper to change FAN voltage.
