### ISSUE TITLE
V3 Board in Production - PT1 Pad  Issue?

### ISSUE THREAD

**Issue by ShockStruck** [LaskaKit/ESP-Vindriktning#7]
Hello,

I currently have the V3 Board in Production at JLPCB and they are stating the following:

"Seems the packages of the PT1 parts cannot match the corresponding pads on the PCB board, so we are unable to assemble them."

The part they are trying to place is a PT26-21B-TR8.

Anyone else experience a similar roadblock when producing the boards?

Thanks!

**Comment by ShockStruck** [comment]
Latest update from JLPCB:

"Our engineer said the part you choose is correct, but the PCB file is wrong." 

Perhaps the V3 Gerber files has some spacing issues on the PT1 pads?

**Comment by Konstantin-G** [comment]
PT1 were not designed exactly for this layout, but there no problems whatsoever, we made 500pcs old version. You can replace it with C55976, so we will do to...
